creditcards:
  issuers:
    - starts with: 34, 37
     lengths: 15
    - starts with: 6011, 644, 645, 646, 647, 648, 649, 65
     lengths: 16, 19
    - starts with: 51, 52, 53, 54, 55
     lengths: 16
    - starts with: 4
      lengths: 13, 16, 19
