server:
  port: 9004

spring:
  datasource:
    url: jdbc:mysql://localhost/drhouse-accountancy?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

drhouse:
  accountancy:
    cost: 90

    credentials:
      - username: walter
        password: secret321
        authorities: ROLE_ACCOUNTANT
      - username: julia
        password: secret123
        authorities: ROLE_ACCOUNTANT

