
server:
  port: 9100

spring:
  datasource:
    url: jdbc:mysql://localhost/udemy-users?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

users:
  app:
    username: instructor
    password: instructor
    authorities: ROLE_APP

  authorities: ROLE_USER
  login:
    message: Login successful


